# Generated by Django 2.2 on 2020-07-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('kind1', models.CharField(max_length=20)),
                ('kind2', models.CharField(max_length=20)),
                ('kind3', models.CharField(max_length=20)),
                ('kind4', models.CharField(max_length=20)),
                ('kind5', models.CharField(max_length=20)),
                ('kind1_note', models.CharField(max_length=200)),
                ('kind2_note', models.CharField(max_length=200)),
                ('kind3_note', models.CharField(max_length=200)),
                ('kind4_note', models.CharField(max_length=200)),
                ('kind5_note', models.CharField(max_length=200)),
            ],
        ),
    ]
